# Trabalho 2

## Configuração de ambiente

Para este trabalho será utilizada a base de dados da FAPESP (fapcov2103). As instruções para carregamento da base estão disponíveis no Moodle da disciplina e requerem ajustes finos de caminhos de arquivo para execução local.

In [2]:
# Valida carregamento da base
%load_ext sql
import pandas.io.sql as pdsql
import pandas as pd
from sqlalchemy import create_engine, text

# Credenciais de execução local, ajuste para sua propria maquina
engine = create_engine('postgresql://postgres:admin@localhost/fapcov2103')
conn = engine.connect()

query = text("""
    SELECT 'Pacientes' AS tabela, Count(*) FROM d2.pacientes
    UNION ALL
    SELECT 'ExamLabs', Count(*) FROM d2.examlabs
    UNION ALL
    SELECT 'Desfechos', Count(*) FROM d2.desfechos;
""")
pdsql.read_sql(query, conn)

/home/felipe/Documents/Usp/2026_2/BigDataMining/.venv/lib/python3.13/site-packages/sql/parse.py:339: SyntaxWarning: invalid escape sequence '\:'
  Given a query, replaces all occurrences of ':variable' with '\:variable' and
/home/felipe/Documents/Usp/2026_2/BigDataMining/.venv/lib/python3.13/site-packages/sql/parse.py:369: SyntaxWarning: invalid escape sequence '\:'
  Given a query, replaces all occurrences of 'example'[x:y] with 'example'[x\:y].

The 'toml' package isn't installed. To load settings from pyproject.toml or ~/.jupysql/config, install with: pip install toml

      tabela    count
0  Pacientes    14673
1   ExamLabs  2952999
2  Desfechos   307928

# O problema

O enunciado requer adicionar à View pivotada (disponível abaixo, vinda do notebook `3.1-PrepDadosWindFunc.ipynb`) algumas colunas através do uso de Window Functions.

```postgresql
CREATE MATERIALIZED VIEW ExamesColesterol AS
    SELECT P.id_paciente, E.dt_coleta, -- 1 secs 326 msec. 13 rows affected.
           MAX(E.de_hospital) AS Hospital,
           AVG(E.de_resultado::FLOAT) FILTER(WHERE E.de_analito ~*'ldl' AND E.de_analito!~*'vldl') AS LDL,              -- evitar contar vldl como ldl.
           AVG(E.de_resultado::FLOAT) FILTER(WHERE E.de_analito ~*'hdl') AS HDL,
           AVG(E.de_resultado::FLOAT) FILTER(WHERE E.de_analito ~*'v.*coles')AS VLDL,
           AVG(E.de_resultado::FLOAT) FILTER(WHERE E.de_analito ~*'n[aã]o.hdl')AS NaoHDL,                               -- aceita nao e não
           AVG(E.de_resultado::FLOAT) FILTER(WHERE Lower(E.de_analito) IN ('colesterol total', 'colesterol')) AS Total, -- alguns hospitais usam só colesterol para indicar total.
           MAX(E.cd_unidade) AS Unidade
        FROM D2.ExamLabs E JOIN D2.Pacientes P on E.id_paciente = P.ID_Paciente
        WHERE  P.CD_Municipio IN('GUARULHOS', 'OSASCO') AND
             E.de_exame ~*'coleste' AND
             E.de_resultado!~'[^\d.,+-]'                -- pode haver texto em vez de números em alguns registros.
        GROUP BY P.id_paciente, E.dt_coleta
```

As colunas pedidas pelo enunciado são:
1. Qual foi o desfecho do atendimento ao paciente que levou à execução
do exame
2. Quantos dias se passaram entre a data da coleta do exame e o desfecho
3. O número sequencial de exames de colesterol desse paciente
4. O número sequencial de exames de colesterol desse atendimento desse
paciente
5. Para os exames do paciente posteriores ao primeiro, indicar a diferença
entre esse analito e a medida anterior (independente de qual seja o
atendimento)

## Item 1

Basta fazer um Join com a tabela de desfechos com base no ID do atendimento. Devido a mudanças na semântica do problema (agora precisamos do atendimento nos items 1, 3 e 4), o agrupamento deve ser por atendimento também, após a data de coleta, pois podem haver mais de um exame em diferentes datas por atendimento.

## Item 2

Basta subtrair da data de desfecho a data de coleta. A data de coleta já é chave de agrupamento, a data de desfecho necessita de desambiguação, logo foi utilizado o máximo, indicando o desfecho final.

## Item 3

Utiliza-se `DENSE_RANK()` particionando por ID do paciente e ordenando por data de coleta, `DENSE_RANK()` é utilizado para não pular nenhum número e empatar exames na mesma data, visto que não há como desambiguar.

## Item 4

Idêntico ao Item 3, mas particiona-se também pelo ID de atendimento.

## Item 5

Para facilitar o SQL, o Item 5 foi implementado em um comando separado da primeira View (apenas a segunda é materializada). Criada a primeira View, com 1 linha por exames de colesterol, criamos uma segunda, adicionando 1 coluna por analito, que utiliza a função `LAG()`, particionando por ID do paciente e ordenando pela data de coleta para calcular a diferença entre exames sucessivos de colesterol.

Segue a abaixo a implementação em SQL.

In [4]:
query = text(r"""
DROP VIEW IF EXISTS ExamesColesterol CASCADE;
DROP MATERIALIZED VIEW IF EXISTS ExamesColesterolDiff;

CREATE VIEW ExamesColesterol AS (
    SELECT P.id_paciente, E.dt_coleta, E.id_atendimento,
        MAX(D.de_desfecho) AS Desfecho, -- Item 1
        MAX(E.de_hospital) AS Hospital,
        MAX(D.dt_desfecho) - E.dt_coleta AS "Dias até desfecho", -- Item 2
        DENSE_RANK() OVER (PARTITION BY P.id_paciente ORDER BY E.dt_coleta) "N° do exame de colesterol do paciente", -- Item 3
        DENSE_RANK() OVER (PARTITION BY P.id_paciente, E.id_atendimento ORDER BY E.dt_coleta) "N° do exame de colesterol do atendimento", -- Item 4
        AVG(REPLACE(E.de_resultado, ',', '.')::FLOAT) FILTER(WHERE E.de_analito ~*'ldl' AND E.de_analito!~*'vldl') AS LDL,
        AVG(REPLACE(E.de_resultado, ',', '.')::FLOAT) FILTER(WHERE E.de_analito ~*'hdl') AS HDL,
        AVG(REPLACE(E.de_resultado, ',', '.')::FLOAT) FILTER(WHERE E.de_analito ~*'v.*coles')AS VLDL,
        AVG(REPLACE(E.de_resultado, ',', '.')::FLOAT) FILTER(WHERE E.de_analito ~*'n[aã]o.hdl')AS NaoHDL,
        AVG(REPLACE(E.de_resultado, ',', '.')::FLOAT) FILTER(WHERE Lower(E.de_analito) IN ('colesterol total', 'colesterol')) AS Total,
        MAX(E.cd_unidade) AS Unidade
    FROM D2.ExamLabs E
        JOIN D2.Pacientes P on E.id_paciente = P.ID_Paciente
        JOIN D2.desfechos D on E.id_atendimento = D.ID_Atendimento -- Item 1
    WHERE
        E.de_exame ~*'coleste' AND
        E.de_resultado!~'[^\d.,+-]'
    GROUP BY P.id_paciente, E.id_atendimento, E.dt_coleta -- Agrupamento com id do atendimento
    ORDER BY P.id_paciente, E.id_atendimento, E.dt_coleta -- ordenação para simplifcar visualização
);

-- Item 5
CREATE MATERIALIZED VIEW ExamesColesterolDiff AS (
    SELECT
        *,
        LDL - LAG(LDL) OVER(PARTITION BY id_paciente ORDER BY dt_coleta) LDL_diff,
        HDL - LAG(HDL) OVER(PARTITION BY id_paciente ORDER BY dt_coleta) HDL_diff,
        VLDL - LAG(VLDL) OVER(PARTITION BY id_paciente ORDER BY dt_coleta) VLDL_diff,
        NaoHDL - LAG(NaoHDL) OVER(PARTITION BY id_paciente ORDER BY dt_coleta) NaoHDL_diff,
        Total - LAG(Total) OVER(PARTITION BY id_paciente ORDER BY dt_coleta) Total_diff
    FROM ExamesColesterol
);
""")
conn.execute(query)

In [6]:
# Query de teste
query = text(r"""
SELECT * FROM ExamesColesterolDiff
ORDER BY COUNT(*) OVER(PARTITION BY id_paciente) DESC, id_paciente, dt_coleta -- Pacientes com mais exames
LIMIT 30;
""")
pdsql.read_sql(query, conn)

,id_paciente,dt_coleta,id_atendimento,desfecho,hospital,Dias até desfecho,N° do exame de colesterol do paciente,N° do exame de colesterol do atendimento,ldl,hdl,vldl,naohdl,total,unidade,ldl_diff,hdl_diff,vldl_diff,naohdl_diff,total_diff
0,6880A9BD5A7975CD5D211AB850CB070B,2020-06-03,ACD87C12E4AD8A8F138E8B08013C8801,Alta Administrativa,HSL,0,1,1,33.0,28.0,24.0,None,85.0,mg/dL,NaN,NaN,NaN,None,NaN
1,6880A9BD5A7975CD5D211AB850CB070B,2020-06-18,F60758AC4ECFB74C2244E50437D9D592,Alta Administrativa,HSL,2,2,1,34.0,21.0,24.0,None,79.0,mg/dL,1.0,-7.0,0.0,None,-6.0
2,6880A9BD5A7975CD5D211AB850CB070B,2020-08-06,528623F15D9C606D214F7F0C77629937,Alta Administrativa,HSL,2,3,1,37.0,20.0,22.0,None,79.0,mg/dL,3.0,-1.0,-2.0,None,0.0
3,6880A9BD5A7975CD5D211AB850CB070B,2020-10-08,E118FE5DF43D38E869467669A9DCA3E9,Alta Administrativa,HSL,2,4,1,44.0,25.0,21.0,None,90.0,mg/dL,7.0,5.0,-1.0,None,11.0
4,6880A9BD5A7975CD5D211AB850CB070B,2020-11-25,7F4F57C23890C83F71D2A0031DCF8ACA,Alta Administrativa,HSL,0,5,1,33.0,34.0,16.0,None,83.0,mg/dL,-11.0,9.0,-5.0,None,-7.0
5,6880A9BD5A7975CD5D211AB850CB070B,2020-12-03,1F8D6D865D6E60044CF5552BF2CFF3A8,Alta Administrativa,HSL,2,6,1,23.0,29.0,24.0,None,76.0,mg/dL,-10.0,-5.0,8.0,None,-7.0
6,6880A9BD5A7975CD5D211AB850CB070B,2020-12-17,CC4B4ECD4FD53354A186B2DD9AA1CCF5,Alta Administrativa,HSL,2,7,1,30.0,24.0,23.0,None,77.0,mg/dL,7.0,-5.0,-1.0,None,1.0
7,6880A9BD5A7975CD5D211AB850CB070B,2021-02-04,FF300A70886282CB482FEFE4FB08E573,Alta Administrativa,HSL,1,8,1,28.0,29.0,17.0,None,74.0,mg/dL,-2.0,5.0,-6.0,None,-3.0
8,6880A9BD5A7975CD5D211AB850CB070B,2021-04-08,BF61014FEACA64FA03DD77B8031D11C0,Alta Administrativa,HSL,1,9,1,31.0,27.0,18.0,None,76.0,mg/dL,3.0,-2.0,1.0,None,2.0
9,6880A9BD5A7975CD5D211AB850CB070B,2021-04-23,AB9D95BF1830FACE69E7B972E8BAFEAD,Alta Administrativa,HSL,0,10,1,34.0,30.0,21.0,None,85.0,mg/dL,3.0,3.0,3.0,None,9.0
10,6880A9BD5A7975CD5D211AB850CB070B,2021-06-03,165AA685E6002FED32327B22832D026A,Alta Administrativa,HSL,2,11,1,29.0,24.0,23.0,None,76.0,mg/dL,-5.0,-6.0,2.0,None,-9.0
11,9D20D9D0DD180407D168AF5A5F560C50,2020-04-10,14C732C711B8FA5F291FE58E903C0D48,Alta Administrativa,HSL,0,1,1,110.0,35.0,26.0,None,171.0,mg/dL,NaN,NaN,NaN,None,NaN
12,9D20D9D0DD180407D168AF5A5F560C50,2020-05-11,8948C006541AB8E1E083645A1FF54DC9,Alta Administrativa,HSL,0,2,1,112.0,44.0,21.0,None,177.0,mg/dL,2.0,9.0,-5.0,None,6.0
13,9D20D9D0DD180407D168AF5A5F560C50,2020-05-27,996C7201003842F5B8ADFC053D6D62F1,Alta Administrativa,HSL,0,3,1,124.0,46.0,24.0,None,194.0,mg/dL,12.0,2.0,3.0,None,17.0
14,9D20D9D0DD180407D168AF5A5F560C50,2020-06-15,E57D49277E6139330B30246856CAEC5B,Alta Administrativa,HSL,0,4,1,115.0,47.0,20.0,None,182.0,mg/dL,-9.0,1.0,-4.0,None,-12.0
15,9D20D9D0DD180407D168AF5A5F560C50,2020-08-17,FBB90A6B30F82A47D36D32A95E67FB1E,Alta Administrativa,HSL,0,5,1,56.0,43.0,19.0,None,118.0,mg/dL,-59.0,-4.0,-1.0,None,-64.0
16,9D20D9D0DD180407D168AF5A5F560C50,2020-10-06,839F3264BB1EC562E2249101B91BFDF6,Alta Administrativa,HSL,0,6,1,47.0,49.0,18.0,None,114.0,mg/dL,-9.0,6.0,-1.0,None,-4.0
17,9D20D9D0DD180407D168AF5A5F560C50,2020-10-27,0C80D8001638796B5ACA0C9A288EA057,Alta Administrativa,HSL,0,7,1,60.0,61.0,17.0,None,138.0,mg/dL,13.0,12.0,-1.0,None,24.0
18,9D20D9D0DD180407D168AF5A5F560C50,2020-12-05,ACDE133FD7E95E51B49B512BCE496E25,Alta Administrativa,HSL,0,8,1,69.0,58.0,24.0,None,151.0,mg/dL,9.0,-3.0,7.0,None,13.0
19,9D20D9D0DD180407D168AF5A5F560C50,2021-01-07,BF2BA1DE01D8ED3B8571FDD248117527,Alta Administrativa,HSL,1,9,1,94.0,36.0,28.0,None,158.0,mg/dL,25.0,-22.0,4.0,None,7.0
20,9D20D9D0DD180407D168AF5A5F560C50,2021-02-09,F4B12DD37370DCFED342F91E2C358880,Alta Administrativa,HSL,1,10,1,68.0,43.0,21.0,None,132.0,mg/dL,-26.0,7.0,-7.0,None,-26.0
21,9D20D9D0DD180407D168AF5A5F560C50,2021-05-26,7D813D2867BF583DBE1FA8367E087329,Alta Administrativa,HSL,0,11,1,71.0,64.0,26.0,None,161.0,mg/dL,3.0,21.0,5.0,None,29.0
22,F4A7B1671073364E0FE785656663B2B7,2020-12-12,D88B9E9278CD5A2ED27EFF273F76FF9E,Alta médica melhorado,HSL,4,1,1,97.0,45.0,35.0,None,177.0,mg/dL,NaN,NaN,NaN,None,NaN
23,F4A7B1671073364E0FE785656663B2B7,2020-12-28,785BBC3E78D1942D8DC99A5505F86588,Alta médica melhorado,HSL,19,2,1,118.0,40.0,40.0,None,198.0,mg/dL,21.0,-5.0,5.0,None,21.0
24,F4A7B1671073364E0FE785656663B2B7,2021-01-13,785BBC3E78D1942D8DC99A5505F86588,Alta médica melhorado,HSL,3,3,2,112.0,21.0,33.0,None,166.0,mg/dL,-6.0,-19.0,-7.0,None,-32.0
25,F4A7B1671073364E0FE785656663B2B7,2021-02-19,3D10F11AC9D1054B7A1B420DDC07F877,Alta médica melhorado,HSL,14,4,1,117.0,32.0,24.0,None,173.0,mg/dL,5.0,11.0,-9.0,None,7.0
26,F4A7B1671073364E0FE785656663B2B7,2021-03-28,11F7F09C259A7F24DB446F5C330ED78D,Alta médica melhorado,HSL,70,5,1,73.0,32.0,55.0,None,160.0,mg/dL,-44.0,0.0,31.0,None,-13.0
27,F4A7B1671073364E0FE785656663B2B7,2021-03-30,11F7F09C259A7F24DB446F5C330ED78D,Alta médica melhorado,HSL,68,6,2,89.0,29.0,51.0,None,169.0,mg/dL,16.0,-3.0,-4.0,None,9.0
28,F4A7B1671073364E0FE785656663B2B7,2021-04-12,11F7F09C259A7F24DB446F5C330ED78D,Alta médica melhorado,HSL,55,7,3,107.0,23.0,40.0,None,170.0,mg/dL,18.0,-6.0,-11.0,None,1.0
29,F4A7B1671073364E0FE785656663B2B7,2021-05-02,11F7F09C259A7F24DB446F5C330ED78D,Alta médica melhorado,HSL,35,8,4,64.0,28.0,105.0,None,197.0,mg/dL,-43.0,5.0,65.0,None,27.0